Keeping the portability.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -116,28 +116,34 @@ if [ "$(/bin/echo ${ODOO_VERSION} | /usr/bin/cut -d'.' -f1)" -gt '17' ]; then
   exit 1
 fi
 
+if [ ! -f "${ODOO_WORK_DIR}/.python-version" ] || [ -L "${ODOO_WORK_DIR}/.python-version" ]; then
+  /bin/echo "INFO: Link ${ODOO_WORK_DIR}/waftlib/templates/${ODOO_VERSION}/.python-version to ${ODOO_WORK_DIR}/.python-version"
+  cd "${ODOO_WORK_DIR}" && /bin/ln -sf "waftlib/templates/${ODOO_VERSION}/.python-version"
+else
+  /bin/echo "WARNING: ${ODOO_WORK_DIR}/.python-version not a default link!"
+fi
+if [ ! -f "${ODOO_WORK_DIR}/.python-version" ]; then
+  /bin/echo "ERROR: You should create .python-version variable file in ${ODOO_WORK_DIR}"
+  exit 1
+fi
+
 # If user pre-installed a virtual-environment and .venv already exists,
 # we do not need pyenv to install python, nor do we need virtualenv,
 # instead the pre-installed version will be used.
 if [ -d "${ODOO_WORK_DIR}/.venv" ]; then
   /bin/echo "INFO: ${ODOO_WORK_DIR}/.venv exist!"
 else
-  if [ ! -f "${ODOO_WORK_DIR}/.python-version" ] || [ -L "${ODOO_WORK_DIR}/.python-version" ]; then
-    /bin/echo "INFO: Link ${ODOO_WORK_DIR}/waftlib/templates/${ODOO_VERSION}/.python-version to ${ODOO_WORK_DIR}/.python-version"
-    cd "${ODOO_WORK_DIR}" && /bin/ln -sf "waftlib/templates/${ODOO_VERSION}/.python-version"
-  else
-    /bin/echo "WARNING: ${ODOO_WORK_DIR}/.python-version not a default link!"
-  fi
-
-  if [ ! -f "${ODOO_WORK_DIR}/.python-version" ]; then
-    /bin/echo "ERROR: You should create .python-version variable in ${ODOO_WORK_DIR}"
+  if [ -f "${ODOO_WORK_DIR}/.venv" ]; then
+    /bin/echo "ERROR: ${ODOO_WORK_DIR}/.venv not a directory!"
     exit 1
   fi
-
   # Install pyenv
-  /bin/chmod 640 "${ODOO_WORK_DIR}/.python-version" || true
   export CFLAGS="-O2"
   export PYENV_ROOT="${ODOO_WORK_DIR}"/.pyenv
+  if [ -f "${ODOO_WORK_DIR}/.pyenv" ]; then
+    /bin/echo "ERROR: ${ODOO_WORK_DIR}/.pyenv not a directory!"
+    exit 1
+  fi
   if [ ! -d "${ODOO_WORK_DIR}/.pyenv" ]; then
     /bin/echo "INFO: Clone https://github.com/pyenv/pyenv in ${PYENV_ROOT}"
     /usr/bin/git clone https://github.com/pyenv/pyenv "${PYENV_ROOT}"
@@ -339,6 +345,7 @@ done
 /bin/chmod 740 "${ODOO_WORK_DIR}/initial-database" || true
 /bin/chmod 740 "${ODOO_WORK_DIR}/install" || true
 /bin/chmod 740 "${ODOO_WORK_DIR}/odoo-service" || true
+/bin/chmod 640 "${ODOO_WORK_DIR}/.python-version" || true
 /bin/chmod 640 "${ODOO_WORK_DIR}/requirements-default.txt" || true
 /bin/chmod 640 "${ODOO_WORK_DIR}/requirements.txt" || true
 /bin/chmod 740 "${ODOO_WORK_DIR}/run" || true
