[IMP] try to upgrade pyenv

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -85,25 +85,24 @@ if [ ! -f "$ODOO_WORK_DIR/.python-version" ]; then
   exit 1
 fi
 
-if [ ! -d $ODOO_WORK_DIR/.pyenv ]; then
-  /bin/echo "INFO: Clone https://github.com/pyenv/pyenv in $ODOO_WORK_DIR/.pyenv"
-  /usr/bin/git clone https://github.com/pyenv/pyenv $ODOO_WORK_DIR/.pyenv
-else
-  /bin/echo "INFO: $ODOO_WORK_DIR/.pyenv exist!"
-fi
-
+# Install pyenv
 export PYENV_ROOT=$ODOO_WORK_DIR/.pyenv
+if [ ! -d $ODOO_WORK_DIR/.pyenv ]; then
+  /bin/echo "INFO: Clone https://github.com/pyenv/pyenv in $PYENV_ROOT"
+  /usr/bin/git clone https://github.com/pyenv/pyenv $PYENV_ROOT
+else
+  /bin/echo "INFO: $ODOO_WORK_DIR/.pyenv exist! Upgrading to latest..."
+  cd $PYENV_ROOT && /usr/bin/git checkout master && /usr/bin/git pull origin master && cd - || { echo 'Failed to upgrade pyenv'; exit 1; }
+fi
 export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
 export PYENV=$PYENV_ROOT/bin/pyenv
-
 eval "$($PYENV init -)"
-
 pyenv install -s
 
+# Install virtualenv
 PYVERSION=$(python -V | /usr/bin/cut -c8-10)
 echo Python version is $PYVERSION
 VIRTUALENV=$ODOO_WORK_DIR/.pyenv/bin/virtualenv.pyz
-
 if [ ! -d $ODOO_WORK_DIR/.venv ]; then
   /bin/echo "INFO: Download $VIRTUALENV"
   /usr/bin/wget --no-check-certificate https://bootstrap.pypa.io/virtualenv/$PYVERSION/virtualenv.pyz -O $VIRTUALENV || { echo 'Download of virtualenv package failed' ; exit 1; }
