[UPD] dont check certificate when downloading virtualenv

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -106,7 +106,7 @@ VIRTUALENV=$ODOO_WORK_DIR/.pyenv/bin/virtualenv.pyz
 
 if [ ! -d $ODOO_WORK_DIR/.venv ]; then
   /bin/echo "INFO: Download $VIRTUALENV"
-  /usr/bin/wget https://bootstrap.pypa.io/virtualenv/$PYVERSION/virtualenv.pyz -O $VIRTUALENV
+  /usr/bin/wget --no-check-certificate https://bootstrap.pypa.io/virtualenv/$PYVERSION/virtualenv.pyz -O $VIRTUALENV || { echo 'Download of virtualenv package failed' ; exit 1; }
   /bin/echo "INFO: Build virtual environment in $ODOO_WORK_DIR/.venv"
   python $VIRTUALENV .venv || { echo 'Virtualenv creation failed' ; exit 1; }
 else
