exit 1 for undefined ODOO_VERSION variable

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -32,8 +32,6 @@ fi
 /bin/mkdir -p $ODOO_WORK_DIR/common/entrypoint.d/
 /bin/mkdir -p $ODOO_WORK_DIR/custom/src/private/
 
-
-
 if [ -f $ODOO_WORK_DIR/.env-shared ]; then
   . $ODOO_WORK_DIR/.env-shared || (/bin/echo "ERROR: Can't load $ODOO_WORK_DIR/.env-shared!" && exit 1)
   if [ -f $ODOO_WORK_DIR/.env-secret ]; then
@@ -44,6 +42,13 @@ if [ -f $ODOO_WORK_DIR/.env-shared ]; then
     . $ODOO_WORK_DIR/.env-secret || (/bin/echo "ERROR: Can't load $ODOO_WORK_DIR/.env-secret!" && exit 1)
   fi
 else
+  if [ -f $ODOO_WORK_DIR/.env-secret ]; then
+    . $ODOO_WORK_DIR/.env-secret || (/bin/echo "ERROR: Can't load $ODOO_WORK_DIR/.env-secret!" && exit 1)
+  else
+    /bin/echo "INFO: Copy $ODOO_WORK_DIR/waftlib/templates/.env-secret to $ODOO_WORK_DIR/."
+    /bin/cp $ODOO_WORK_DIR/waftlib/templates/.env-secret $ODOO_WORK_DIR/
+    . $ODOO_WORK_DIR/.env-secret || (/bin/echo "ERROR: Can't load $ODOO_WORK_DIR/.env-secret!" && exit 1)
+  fi
   if [ "$ODOO_VERSION" = '' ] ; then
     /bin/echo "ERROR: You should define 'ODOO_VERSION' variable in $ODOO_WORK_DIR/.env-secret"
     exit 1
