Before merging.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -3,13 +3,6 @@
 
 set -e
 
-# Determine the correct `sed` command
-if [ "$(uname)" = "Darwin" ]; then
-  SED_CMD="/usr/bin/sed"
-else
-  SED_CMD="/bin/sed"
-fi
-
 SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
 ODOO_WORK_DIR="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
 cd "${ODOO_WORK_DIR}"
@@ -84,7 +77,7 @@ else
     /bin/echo "ERROR: You should define 'ODOO_VERSION' variable in "${ODOO_WORK_DIR}/.env-secret"."
     exit 1
   else
-    if [ "$($SED_CMD -E 's/^[0-9]+\.[0-9]+$//' <<< "${ODOO_VERSION}")" != "" ]; then
+    if [ "$(/bin/echo "${ODOO_VERSION}" | /usr/bin/sed 's/^[0-9]\+'\.'[0-9]\+$//')" != '' ] ; then
       /bin/echo "ERROR: 'ODOO_VERSION' does not a floating number!"
       exit 1
     else
@@ -107,7 +100,7 @@ if [ "${ODOO_VERSION}" = '' ] ; then
   /bin/echo "ERROR: You should define 'ODOO_VERSION' variable in "${ODOO_WORK_DIR}/.env-secret""
   exit 1
 else
-  if [ "$($SED_CMD -E 's/^[0-9]+\.[0-9]+$//' <<< "${ODOO_VERSION}")" != "" ]; then
+  if [ "$(/bin/echo "${ODOO_VERSION}" | /usr/bin/sed 's/^[0-9]\+'\.'[0-9]\+$//')" != '' ] ; then
     /bin/echo "ERROR: 'ODOO_VERSION' does not a floating number!"
     exit 1
   fi
@@ -163,21 +156,16 @@ else
   eval "$("${PYENV}" init -)"
   "${PYENV}" install -s
 
-  PYVERSION="$(python -V 2>&1 | $SED_CMD 's/^Python //; s/\.[0-9]*$//')"
+  PYVERSION="$(python -V 2>&1 | /usr/bin/sed 's/^Python //; s/\.[0-9]*$//')"
   /bin/echo "Python version is ${PYVERSION}"
 
   # Install virtualenv
   VIRTUALENV="${PYENV_ROOT}/bin/virtualenv.pyz"
   /bin/echo "INFO: Download ${VIRTUALENV}"
-  # /usr/bin/wget --no-check-certificate "https://bootstrap.pypa.io/virtualenv/${PYVERSION}/virtualenv.pyz" -O "${VIRTUALENV}" || { /bin/echo 'Download of virtualenv package failed' ; exit 1; }
-  if command -v wget > /dev/null; then
-    wget --no-check-certificate "https://bootstrap.pypa.io/virtualenv/${PYVERSION}/virtualenv.pyz" -O "${VIRTUALENV}" || { /bin/echo 'Download of virtualenv package failed'; exit 1; }
-  elif command -v curl > /dev/null; then
-    curl -L "https://bootstrap.pypa.io/virtualenv/${PYVERSION}/virtualenv.pyz" -o "${VIRTUALENV}" || { /bin/echo 'Download of virtualenv package failed'; exit 1; }
-  else
-    echo "ERROR: Neither wget nor curl is available for downloading files."
-    exit 1
-  fi
+  (/usr/bin/wget --no-check-certificate "https://bootstrap.pypa.io/virtualenv/${PYVERSION}/virtualenv.pyz" -O "${VIRTUALENV}" || \
+  (/bin/echo "INFO: /usr/bin/wget did not download virtualenv package, try /usr/bin/curl ..." && \
+  /usr/bin/curl -L "https://bootstrap.pypa.io/virtualenv/${PYVERSION}/virtualenv.pyz" -o "${VIRTUALENV}")) || \
+  { /bin/echo 'ERROR: Download of virtualenv package failed!'; exit 1; }
 
   /bin/echo "INFO: Build virtual environment in ${ODOO_WORK_DIR}/.venv"
   python "${VIRTUALENV}" .venv || { /bin/echo 'Virtualenv creation failed' ; exit 1; }
