[IMP] Make it possible to use existing python installation

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -116,45 +116,49 @@ if [ "$(/bin/echo ${ODOO_VERSION} | /usr/bin/cut -d'.' -f1)" -gt '17' ]; then
   exit 1
 fi
 
-if [ ! -f "${ODOO_WORK_DIR}/.python-version" ] || [ -L "${ODOO_WORK_DIR}/.python-version" ]; then
-  /bin/echo "INFO: Link ${ODOO_WORK_DIR}/waftlib/templates/${ODOO_VERSION}/.python-version to ${ODOO_WORK_DIR}/.python-version"
-  cd "${ODOO_WORK_DIR}" && /bin/ln -sf "waftlib/templates/${ODOO_VERSION}/.python-version"
+# If user pre-installed a virtual-environment and .venv already exists,
+# we do not need pyenv to install python, nor do we need virtualenv,
+# instead the pre-installed version will be used.
+if [ -d "${ODOO_WORK_DIR}/.venv" ]; then
+  /bin/echo "INFO: ${ODOO_WORK_DIR}/.venv exist!"
 else
-  /bin/echo "WARNING: ${ODOO_WORK_DIR}/.python-version not a default link!"
-fi
+  if [ ! -f "${ODOO_WORK_DIR}/.python-version" ] || [ -L "${ODOO_WORK_DIR}/.python-version" ]; then
+    /bin/echo "INFO: Link ${ODOO_WORK_DIR}/waftlib/templates/${ODOO_VERSION}/.python-version to ${ODOO_WORK_DIR}/.python-version"
+    cd "${ODOO_WORK_DIR}" && /bin/ln -sf "waftlib/templates/${ODOO_VERSION}/.python-version"
+  else
+    /bin/echo "WARNING: ${ODOO_WORK_DIR}/.python-version not a default link!"
+  fi
 
-if [ ! -f "${ODOO_WORK_DIR}/.python-version" ]; then
-  /bin/echo "ERROR: You should create .python-version variable in ${ODOO_WORK_DIR}"
-  exit 1
-fi
+  if [ ! -f "${ODOO_WORK_DIR}/.python-version" ]; then
+    /bin/echo "ERROR: You should create .python-version variable in ${ODOO_WORK_DIR}"
+    exit 1
+  fi
 
-# Install pyenv
-export CFLAGS="-O2"
-export PYENV_ROOT="${ODOO_WORK_DIR}"/.pyenv
-if [ ! -d "${ODOO_WORK_DIR}/.pyenv" ]; then
-  /bin/echo "INFO: Clone https://github.com/pyenv/pyenv in ${PYENV_ROOT}"
-  /usr/bin/git clone https://github.com/pyenv/pyenv "${PYENV_ROOT}"
-else
-  /bin/echo "INFO: ${ODOO_WORK_DIR}/.pyenv exist! Upgrading to latest..."
-  cd "${PYENV_ROOT}" && /usr/bin/git checkout master && /usr/bin/git pull origin master && cd - || { /bin/echo 'Failed to upgrade pyenv'; exit 1; }
-fi
-PATH="${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${PATH}"
-PYENV="${PYENV_ROOT}/bin/pyenv"
-eval "$("${PYENV}" init -)"
-"${PYENV}" install -s
+  # Install pyenv
+  /bin/chmod 640 "${ODOO_WORK_DIR}/.python-version" || true
+  export CFLAGS="-O2"
+  export PYENV_ROOT="${ODOO_WORK_DIR}"/.pyenv
+  if [ ! -d "${ODOO_WORK_DIR}/.pyenv" ]; then
+    /bin/echo "INFO: Clone https://github.com/pyenv/pyenv in ${PYENV_ROOT}"
+    /usr/bin/git clone https://github.com/pyenv/pyenv "${PYENV_ROOT}"
+  else
+    /bin/echo "INFO: ${ODOO_WORK_DIR}/.pyenv exist! Upgrading to latest..."
+    cd "${PYENV_ROOT}" && /usr/bin/git checkout master && /usr/bin/git pull origin master && cd - || { /bin/echo 'Failed to upgrade pyenv'; exit 1; }
+  fi
+  PATH="${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${PATH}"
+  PYENV="${PYENV_ROOT}/bin/pyenv"
+  eval "$("${PYENV}" init -)"
+  "${PYENV}" install -s
 
-# Install virtualenv
-PYVERSION="$(python -V 2>&1 | /bin/sed 's/^Python //; s/\.[0-9]*$//')"
+  PYVERSION="$(python -V 2>&1 | /bin/sed 's/^Python //; s/\.[0-9]*$//')"
+  /bin/echo "Python version is ${PYVERSION}"
 
-/bin/echo "Python version is ${PYVERSION}"
-VIRTUALENV="${PYENV_ROOT}/bin/virtualenv.pyz"
-if [ ! -d "${ODOO_WORK_DIR}/.venv" ]; then
+  # Install virtualenv
+  VIRTUALENV="${PYENV_ROOT}/bin/virtualenv.pyz"
   /bin/echo "INFO: Download ${VIRTUALENV}"
   /usr/bin/wget --no-check-certificate "https://bootstrap.pypa.io/virtualenv/${PYVERSION}/virtualenv.pyz" -O "${VIRTUALENV}" || { /bin/echo 'Download of virtualenv package failed' ; exit 1; }
   /bin/echo "INFO: Build virtual environment in ${ODOO_WORK_DIR}/.venv"
   python "${VIRTUALENV}" .venv || { /bin/echo 'Virtualenv creation failed' ; exit 1; }
-else
-  /bin/echo "INFO: ${ODOO_WORK_DIR}/.venv exist!"
 fi
 
 if [ ! -f "${ODOO_WORK_DIR}/build" ] || [ -L "${ODOO_WORK_DIR}/build" ]; then
@@ -335,7 +339,6 @@ done
 /bin/chmod 740 "${ODOO_WORK_DIR}/initial-database" || true
 /bin/chmod 740 "${ODOO_WORK_DIR}/install" || true
 /bin/chmod 740 "${ODOO_WORK_DIR}/odoo-service" || true
-/bin/chmod 640 "${ODOO_WORK_DIR}/.python-version" || true
 /bin/chmod 640 "${ODOO_WORK_DIR}/requirements-default.txt" || true
 /bin/chmod 640 "${ODOO_WORK_DIR}/requirements.txt" || true
 /bin/chmod 740 "${ODOO_WORK_DIR}/run" || true
