exit 1 for undefined ODOO_VERSION variable

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -32,19 +32,58 @@ fi
 /bin/mkdir -p $ODOO_WORK_DIR/common/entrypoint.d/
 /bin/mkdir -p $ODOO_WORK_DIR/custom/src/private/
 
-if [ ! -f $ODOO_WORK_DIR/.env-secret ]; then
+if [ -f $ODOO_WORK_DIR/.env-secret ]; then
+  . $ODOO_WORK_DIR/.env-secret
+  if [ -f $ODOO_WORK_DIR/.env-shared ]; then
+    if [ -L $ODOO_WORK_DIR/.env-shared ]; then
+      if [ ! -d $ODOO_WORK_DIR/waftlib ]; then
+        . $ODOO_WORK_DIR/.env-shared && \
+        . $ODOO_WORK_DIR/.env-secret
+      else
+        ODOO_VERSION="$(/bin/ls -lha | /bin/grep $ODOO_WORK_DIR/.env-shared | /usr/bin/cut -d '/' -f3)" && \
+        . $ODOO_WORK_DIR/.env-secret
+      fi
+    else
+      . $ODOO_WORK_DIR/.env-shared && \
+      . $ODOO_WORK_DIR/.env-secret
+    fi
+  else
+    if [[ $ODOO_VERSION =~ ^[+-]?[0-9]+\.?[0-9]*$ ]] ; then
+      /bin/echo "INFO: Link $ODOO_WORK_DIR/waftlib/templates/$ODOO_VERSION/.env-shared to $ODOO_WORK_DIR/.env-shared"
+      cd $ODOO_WORK_DIR && /bin/ln -sf waftlib/templates/$ODOO_VERSION/.env-shared
+    fi
+      /bin/echo "ERROR: 'ODOO_VERSION' does not define or it is not a floating number!"
+      exit 1
+    fi
+  fi
+else
   /bin/echo "INFO: Copy $ODOO_WORK_DIR/waftlib/templates/.env-secret to $ODOO_WORK_DIR/."
   /bin/cp $ODOO_WORK_DIR/waftlib/templates/.env-secret $ODOO_WORK_DIR/
-fi
-
-if [ ! -f $ODOO_WORK_DIR/.env-shared ] || [ -L $ODOO_WORK_DIR/.env-shared ]; then
-  . $ODOO_WORK_DIR/.env-secret
-  if [ "$ODOO_VERSION" != "" ]; then
-    /bin/echo "INFO: Link $ODOO_WORK_DIR/waftlib/templates/$ODOO_VERSION/.env-shared to $ODOO_WORK_DIR/.env-shared"
-    cd $ODOO_WORK_DIR && /bin/ln -sf waftlib/templates/$ODOO_VERSION/.env-shared
+  if [ -f $ODOO_WORK_DIR/.env-shared ]; then
+    if [ -L $ODOO_WORK_DIR/.env-shared ]; then
+      if [ ! -d $ODOO_WORK_DIR/waftlib ]; then
+        . $ODOO_WORK_DIR/.env-shared && \
+        . $ODOO_WORK_DIR/.env-secret
+      else
+        ODOO_VERSION="$(/bin/ls -lha | /bin/grep $ODOO_WORK_DIR/.env-shared | /usr/bin/cut -d '/' -f3)"
+      fi
+    else
+      . $ODOO_WORK_DIR/.env-shared && \
+      . $ODOO_WORK_DIR/.env-secret
+    fi
   else
-    /bin/echo "ERROR: You should define 'ODOO_VERSION' variable in $ODOO_WORK_DIR/.env-secret"
-    exit 1
+    if [[ $ODOO_VERSION == '' ]] ; then
+      /bin/echo "ERROR: You should define 'ODOO_VERSION' variable in $ODOO_WORK_DIR/.env-secret"
+      exit 1
+    else
+      if [[ $ODOO_VERSION =~ ^[+-]?[0-9]+\.?[0-9]*$ ]] ; then
+        /bin/echo "INFO: Link $ODOO_WORK_DIR/waftlib/templates/$ODOO_VERSION/.env-shared to $ODOO_WORK_DIR/.env-shared"
+        cd $ODOO_WORK_DIR && /bin/ln -sf waftlib/templates/$ODOO_VERSION/.env-shared
+      fi
+        /bin/echo "ERROR: 'ODOO_VERSION' does not a floating number!"
+        exit 1
+      fi
+    fi
   fi
 fi
 
